version: 2
jobs:
  build:
    docker:
      - image: stronglytyped/atmel-avr-toolchain-build:latest
    steps:
      - checkout
      - run:
          name: Look around
          command: ls -la
      - run:
          name: Build Toolchain
          command: bash build.sh
          no_output_timeout: 3600
      - run:
          name: Create Tarball
          command: tar cjf /tmp/avr-gcc.tar.bz2 avr-gcc
      - store_artifacts:
          path: /tmp/avr-gcc.tar.bz2
          destination: avr-gcc.tar.bz2
